### ISSUE TITLE
support circle nms?

### ISSUE THREAD

**Issue by AndyYuan96** [gdlg/pytorch_nms#5]
Hi, gdlg, thanks you for so excellent job, I just wonder if you will add support for circle nms, nms according to circle's center and radius.

**Comment by gdlg** [comment]
Hi Andy,

I am sorry for the late response. I am afraid that I haven’t planned to add circle NMS in the near future however you are welcome to fork this repository or create a pull request. It should be fairly simple to implement. 

If you would like to implement it, you need to modify the function devIoU in nms_kernel.cu to define the new overlap criteria. There are also a few places in the same file
where you need to change the array stride (currently 4) to fit the
number of attributes that you need for circle (centre + radius = 3?) and perhaps
replace line 74–81 with a loop. Apart from that, the rest of the code should be agnostic to the type of geometry that you are using.

**Comment by AndyYuan96** [comment]
> Hi Andy,
> 
> I am sorry for the late response. I am afraid that I haven’t planned to add circle NMS in the near future however you are welcome to fork this repository or create a pull request. It should be fairly simple to implement.
> 
> If you would like to implement it, you need to modify the function devIoU in nms_kernel.cu to define the new overlap criteria. There are also a few places in the same file
> where you need to change the array stride (currently 4) to fit the
> number of attributes that you need for circle (centre + radius = 3?) and perhaps
> replace line 74–81 with a loop. Apart from that, the rest of the code should be agnostic to the type of geometry that you are using.

thanks you, I already fininshed, it's quiet easy.
